### ISSUE TITLE
missing dependency, devicesettings

### ISSUE THREAD

**Issue by Loader009** [tdm/android_device_idealte_msm8998-common#1]
https://github.com/LineageOS/android_packages_resources_devicesettings

in this file: lineage.dependencies
https://github.com/tdm/android_device_idealte_msm8998-common/blob/lineage-16.0/lineage.dependencies

we need the following dependency:
```
  {
    "repository": "android_packages_resources_devicesettings",
    "target_path": "packages/resources/devicesettings"
  }
```

**Comment by Gigadoc2** [comment]
AFAIK this tree began as a copy of https://github.com/LineageOS/android_device_oneplus_msm8998-common/tree/lineage-16.0, which might explain why this is missing: It had a dependency on oppo-common which in turn had a dependency on devicesettings.

**Comment by Loader009** [comment]
Be aware that this pull https://github.com/tdm/android_device_fxtec_pro1/pull/12 is also adding the dependency to https://github.com/tdm/android_device_fxtec_pro1/blob/lineage-16.0/lineage.dependencies .
I think the dependency should be in this repo, but I am not really experienced in this.

**Comment by Loader009** [comment]
This repo seems to be obsolete now.
closing
